package com.sa.java.modules.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPerson(java.lang.String person) {
		set("person", person);
	}

	public java.lang.String getPerson() {
		return get("person");
	}

	public void setBeginDate(java.lang.String beginDate) {
		set("begin_date", beginDate);
	}

	public java.lang.String getBeginDate() {
		return get("begin_date");
	}

	public void setEndDate(java.lang.String endDate) {
		set("end_date", endDate);
	}

	public java.lang.String getEndDate() {
		return get("end_date");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
