package com.sa.java.modules.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShow<M extends BaseShow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setZoneId(java.lang.String zoneId) {
		set("zoneId", zoneId);
	}

	public java.lang.String getZoneId() {
		return get("zoneId");
	}

	public void setShowId(java.lang.String showId) {
		set("showId", showId);
	}

	public java.lang.String getShowId() {
		return get("showId");
	}

	public void setShowName(java.lang.String showName) {
		set("showName", showName);
	}

	public java.lang.String getShowName() {
		return get("showName");
	}

}
