package com.sa.java.modules.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStreamMediaServerHost(java.lang.String streamMediaServerHost) {
		set("stream_media_server_host", streamMediaServerHost);
	}

	public java.lang.String getStreamMediaServerHost() {
		return get("stream_media_server_host");
	}

	public void setShowFilePath(java.lang.String showFilePath) {
		set("show_file_path", showFilePath);
	}

	public java.lang.String getShowFilePath() {
		return get("show_file_path");
	}

}
