package com.sa.java.modules.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSceneryHost<M extends BaseSceneryHost<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSceneryId(java.lang.String sceneryId) {
		set("scenery_id", sceneryId);
	}

	public java.lang.String getSceneryId() {
		return get("scenery_id");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setPort(java.lang.Integer port) {
		set("port", port);
	}

	public java.lang.Integer getPort() {
		return get("port");
	}

}
