package com.sa.java.modules.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("config", "id", Config.class);
		arp.addMapping("scenery_dict", "zoneId", SceneryDict.class);
		arp.addMapping("scenery_host", "id", SceneryHost.class);
		arp.addMapping("scenery_show", "id", SceneryShow.class);
		arp.addMapping("task", "id", Task.class);
	}
}

