package com.sa.java.modules.model;

import com.sa.java.modules.model.base.BaseSceneryShow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SceneryShow extends BaseSceneryShow<SceneryShow> {
	public static final SceneryShow dao = new SceneryShow();
}
