package com.sa.java.modules.model;

import com.sa.java.modules.model.base.BaseSceneryDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SceneryDict extends BaseSceneryDict<SceneryDict> {
	public static final SceneryDict dao = new SceneryDict();

}
