package com.sa.java.modules.model;

import com.sa.java.modules.model.base.BaseSceneryHost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SceneryHost extends BaseSceneryHost<SceneryHost> {
	public static final SceneryHost dao = new SceneryHost();
}
